apiVersion: v1
kind: Service
metadata:
  name: settlement
  namespace: exchange
  labels:
    app: settlement
spec:
  type: ClusterIP
  selector:
    app: settlement
  ports:
    - name: http
      port: 8083
      targetPort: http
